apiVersion: apps/v1
kind: Deployment
metadata:
    name: mlops-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: mlops
    template:
        metadata:
            labels:
                app: mlops                
        spec:
            containers:
            - name: mlops-container
              image: orson7420/mlops_model:latest
              ports:
              - containerPort: 8000